Repository nolar/kopf, pull requests merged in 2020-10, with the labels that each got.

#558 Enrich the K8s API errors with information from K8s API itself
  kopf/clients/discovery.py
  kopf/clients/errors.py
  kopf/clients/events.py
  kopf/clients/fetching.py
  kopf/clients/patching.py
  kopf/clients/watching.py
  tests/handling/test_error_handling.py
  tests/k8s/test_errors.py
Labels: enhancement

#559 Hide warnings on fake inconsistencies when patching the nonexistent objects
  kopf/clients/patching.py
  kopf/reactor/effects.py
  kopf/structs/diffs.py
  tests/diffs/test_calculation.py
  tests/k8s/test_patching.py
  tests/reactor/test_patching_inconsistencies.py
Labels: enhancement

#563 Fix the old PyPI credentials to release 0.27.1 (for Python 3.9 support)
  .travis.yml
Labels: automation

#567 Use Configuration.get_default_copy
  kopf/utilities/piggybacking.py
Labels: enhancement

#568 Fix authentication in CLI commands for peering
  kopf/cli.py
Labels: bug

#569 Shorten peering ids, filter out IPv6/ARPA names
  kopf/cli.py
  kopf/engines/peering.py
  kopf/reactor/running.py
  kopf/utilities/hostnames.py
  tests/peering/test_id_generation.py
Labels: enhancement
