Repository nolar/kopf, pull requests merged in 2021-02, with the labels that each got.

#666 Add missing `memo` kwargs to callback protocols
  examples/12-embedded/example.py
  kopf/__init__.py
  kopf/reactor/causation.py
  kopf/structs/callbacks.py
  kopf/structs/containers.py
  kopf/structs/memos.py
  tests/basic-structs/test_containers.py
  tests/basic-structs/test_memos.py
  tests/hierarchies/test_contextual_owner.py
  tests/invocations/test_kwargs.py
  tests/lifecycles/test_real_invocation.py
  tests/registries/conftest.py
Labels: refactoring

#667 Operator-level memos, optionally passed into embedded operators
  docs/index.rst
  docs/kwargs.rst
  docs/memories.rst
  examples/12-embedded/example.py
  kopf/engines/probing.py
  kopf/reactor/activities.py
  kopf/reactor/causation.py
  kopf/reactor/invocation.py
  kopf/reactor/processing.py
  kopf/reactor/running.py
  kopf/structs/callbacks.py
  kopf/structs/containers.py
  kopf/structs/memos.py
  tests/authentication/test_authentication.py
  tests/basic-structs/test_causes.py
  tests/basic-structs/test_containers.py
  tests/handling/daemons/conftest.py
  tests/handling/test_activity_triggering.py
  tests/handling/test_cause_handling.py
  tests/handling/test_cause_logging.py
  tests/handling/test_delays.py
  tests/handling/test_error_handling.py
  tests/handling/test_event_handling.py
  tests/handling/test_multistep.py
  tests/handling/test_no_handlers.py
  tests/handling/test_parametrization.py
  tests/handling/test_retrying_limits.py
  tests/handling/test_timing_consistency.py
  tests/invocations/test_kwargs.py
  tests/registries/conftest.py
  tests/test_liveness.py
Labels: enhancement

#669 Test with extras optionally installed
  .github/workflows/ci.yaml
  .github/workflows/thorough.yaml
  tests/cli/test_logging.py
Labels: automation

#670 Prevent log spill in CI tests
  tests/logging/conftest.py
  tests/logging/test_configuration.py
  tests/logging/test_loggers.py
Labels: automation

#671 Give some care to the hierarchies toolkit
  docs/hierarchies.rst
  kopf/toolkits/hierarchies.py
  tests/hierarchies/test_contextual_owner.py
  tests/hierarchies/test_labelling.py
  tests/hierarchies/test_name_harmonizing.py
  tests/hierarchies/test_namespace_adjusting.py
  tests/hierarchies/test_owner_referencing.py
  tests/hierarchies/test_type_validation.py
Labels: enhancement

#672 Support 3rd-party clients in the hierarchy toolkit
  docs/hierarchies.rst
  kopf/structs/dicts.py
  kopf/toolkits/hierarchies.py
  kopf/utilities/thirdparty.py
  tests/conftest.py
  tests/dicts/test_resolving.py
  tests/hierarchies/conftest.py
  tests/hierarchies/test_labelling.py
  tests/hierarchies/test_name_harmonizing.py
  tests/hierarchies/test_namespace_adjusting.py
  tests/hierarchies/test_owner_referencing.py
  tests/test_thirdparty.py
Labels: enhancement

#674 Deduplicate handlers by their target fields instead of fn alone
  docs/filters.rst
  docs/kwargs.rst
  docs/resources.rst
  kopf/on.py
  kopf/reactor/registries.py
  tests/registries/test_decorators.py
  tests/registries/test_matching_for_changing.py
Labels: breaking, bug

#677 Upgrade mypy to v0.800
  kopf/utilities/thirdparty.py
  requirements.txt
Labels: automation

#675 Stop daemons & timers while the operator is on peering freeze
  kopf/reactor/daemons.py
  kopf/reactor/orchestration.py
  kopf/reactor/running.py
  kopf/structs/primitives.py
  tests/handling/daemons/conftest.py
  tests/handling/daemons/test_daemon_termination.py
Labels: bug

#665 fix liveness probe parameter in docs
  docs/probing.rst
Labels: documentation

#679 Extract `sleep_or_wait()` to async primitives
  kopf/engines/peering.py
  kopf/reactor/activities.py
  kopf/reactor/daemons.py
  kopf/reactor/effects.py
  kopf/structs/primitives.py
  tests/handling/conftest.py
  tests/handling/test_activity_triggering.py
  tests/peering/test_freeze_mode.py
  tests/timing/test_sleeping.py
  tests/timing/test_throttling.py
Labels: refactoring

#680 Change terminology from "freezing" to "pausing"
  DEVELOPMENT.md
  docs/peering.rst
  examples/06-peering/README.md
  kopf/cli.py
  kopf/clients/watching.py
  kopf/engines/peering.py
  kopf/reactor/daemons.py
  kopf/reactor/observation.py
  kopf/reactor/orchestration.py
  kopf/reactor/queueing.py
  kopf/reactor/running.py
  kopf/structs/configuration.py
  kopf/structs/primitives.py
  tests/handling/daemons/conftest.py
  tests/handling/daemons/test_daemon_termination.py
  tests/k8s/test_watching_continuously.py
  tests/k8s/test_watching_with_freezes.py
  tests/orchestration/test_task_adjustments.py
  tests/peering/test_freeze_mode.py
Labels: refactoring

#681 Change terminology for streams of events
  kopf/engines/peering.py
  kopf/reactor/effects.py
  kopf/reactor/observation.py
  kopf/reactor/processing.py
  kopf/reactor/queueing.py
  tests/handling/daemons/conftest.py
  tests/handling/test_cause_handling.py
  tests/handling/test_cause_logging.py
  tests/handling/test_delays.py
  tests/handling/test_error_handling.py
  tests/handling/test_event_handling.py
  tests/handling/test_multistep.py
  tests/handling/test_no_handlers.py
  tests/handling/test_parametrization.py
  tests/handling/test_retrying_limits.py
  tests/handling/test_timing_consistency.py
  tests/observation/test_processing_of_namespaces.py
  tests/observation/test_processing_of_resources.py
  tests/orchestration/test_task_adjustments.py
  tests/peering/test_freeze_mode.py
  tests/reactor/test_queueing.py
Labels: refactoring

#695 Rename `memories` → `memos` & `ephemera`
  docs/index.rst
  docs/kwargs.rst
  docs/memos.rst
  kopf/__init__.py
  kopf/engines/probing.py
  kopf/reactor/activities.py
  kopf/reactor/causation.py
  kopf/reactor/processing.py
  kopf/reactor/running.py
  kopf/structs/callbacks.py
  kopf/structs/containers.py
  kopf/structs/ephemera.py
  tests/authentication/test_authentication.py
  tests/basic-structs/test_containers.py
  tests/basic-structs/test_memos.py
  tests/handling/daemons/conftest.py
  tests/handling/test_activity_triggering.py
  tests/handling/test_cause_handling.py
  tests/handling/test_cause_logging.py
  tests/handling/test_delays.py
  tests/handling/test_error_handling.py
  tests/handling/test_event_handling.py
  tests/handling/test_multistep.py
  tests/handling/test_no_handlers.py
  tests/handling/test_parametrization.py
  tests/handling/test_retrying_limits.py
  tests/handling/test_timing_consistency.py
  tests/hierarchies/test_contextual_owner.py
  tests/invocations/test_kwargs.py
  tests/lifecycles/test_real_invocation.py
  tests/registries/conftest.py
  tests/test_liveness.py
Labels: refactoring

#696 Improve and align throttling error reporting in Python 3.7 with 3.8+
  kopf/reactor/effects.py
  tests/timing/test_throttling.py
Labels: bug
