Repository nolar/kopf, pull requests merged in 2021-07, with the labels that each got.

#794 Drop Kubernetes 1.16 & 1.17, thus CRD v1beta1
  .github/workflows/ci.yaml
  .github/workflows/thorough.yaml
  docs/walkthrough/resources.rst
  examples/09-testing/test_example_09.py
  examples/11-filtering-handlers/test_example_11.py
  examples/crd-v1beta1.yaml
  examples/crd.yaml
  peering-v1beta1.yaml
  peering.yaml
  tests/e2e/conftest.py
Labels: automation

#793 Configure networking timeouts for API clients
  docs/configuration.rst
  kopf/_cogs/clients/api.py
  kopf/_cogs/clients/creating.py
  kopf/_cogs/clients/events.py
  kopf/_cogs/clients/fetching.py
  kopf/_cogs/clients/patching.py
  kopf/_cogs/clients/scanning.py
  kopf/_cogs/clients/watching.py
  kopf/_cogs/configs/configuration.py
  kopf/_core/actions/application.py
  kopf/_core/engines/admission.py
  kopf/_core/engines/daemons.py
  kopf/_core/engines/peering.py
  kopf/_core/engines/posting.py
  kopf/_core/reactor/observation.py
  kopf/_core/reactor/running.py
  kopf/_kits/webhooks.py
  tests/apis/test_api_requests.py
  tests/conftest.py
  tests/k8s/test_creating.py
  tests/k8s/test_events.py
  tests/k8s/test_list_objs.py
  tests/k8s/test_patching.py
  tests/k8s/test_scanning.py
  tests/observation/test_processing_of_resources.py
  tests/posting/test_poster.py
  tests/reactor/test_patching_inconsistencies.py
  tests/settings/test_defaults.py
Labels: enhancement

#795 Return the connection to the pool as soon as it is parsed
  kopf/_cogs/clients/api.py
Labels: refactoring

#788 Retry all K8s API operations on networking/server-side errors
  docs/configuration.rst
  kopf/_cogs/clients/api.py
  kopf/_cogs/clients/creating.py
  kopf/_cogs/clients/errors.py
  kopf/_cogs/clients/events.py
  kopf/_cogs/clients/fetching.py
  kopf/_cogs/clients/patching.py
  kopf/_cogs/clients/scanning.py
  kopf/_cogs/clients/watching.py
  kopf/_cogs/configs/configuration.py
  kopf/_core/actions/application.py
  kopf/_core/engines/admission.py
  kopf/_core/engines/peering.py
  kopf/_core/engines/posting.py
  kopf/_core/reactor/observation.py
  kopf/_kits/webhooks.py
  tests/apis/test_api_requests.py
  tests/apis/test_error_retries.py
  tests/conftest.py
  tests/k8s/conftest.py
  tests/k8s/test_creating.py
  tests/k8s/test_errors.py
  tests/k8s/test_events.py
  tests/k8s/test_list_objs.py
  tests/k8s/test_patching.py
  tests/k8s/test_scanning.py
Labels: enhancement

#732 Prevent loss of events under stress-load or sync-blockers
  kopf/_core/reactor/queueing.py
Labels: bug

#786 Upgrade to mypy 0.910 and fix the issues
  .github/workflows/ci.yaml
  .github/workflows/thorough.yaml
  .pre-commit-config.yaml
  kopf/_cogs/aiokits/aiotasks.py
  kopf/_cogs/helpers/loaders.py
  kopf/_kits/runner.py
  kopf/cli.py
  requirements.txt
Labels: automation

#804 Convert issue templates to issue forms
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yaml
Labels: automation

#803 Modify JSONPatch to include `add` operation on missing keys
  CONTRIBUTORS.md
  kopf/_cogs/structs/patches.py
  kopf/_core/engines/admission.py
  tests/admission/test_jsonpatch.py
  tests/admission/test_serving_responses.py
Labels: enhancement
