Repository nolar/kopf, pull requests merged in 2021-05, with the labels that each got.

#747 Accept arbitrary types for memos & results, clarify other kwarg types
  examples/12-embedded/example.py
  kopf/__init__.py
  kopf/reactor/running.py
  kopf/structs/callbacks.py
  kopf/structs/containers.py
  kopf/structs/ephemera.py
Labels: bug

#750 Remove leading zeros from IPv4 in tests
  tests/admission/test_certificates.py
Labels: automation

#749 Correct GHA badge link in README
  README.md
Labels: documentation

#751 Remove obsolete handler fns in registries
  kopf/reactor/registries.py
Labels: refactoring

#753 Fix improper memo creation
  kopf/structs/containers.py
  tests/basic-structs/test_memories.py
Labels: bug

#752 Isolate low-level "invocation" from higher-level "causation" & "callbacks"
  kopf/reactor/causation.py
  kopf/reactor/handling.py
  kopf/reactor/invocation.py
  kopf/reactor/registries.py
  kopf/structs/callbacks.py
  kopf/structs/handlers.py
  tests/basic-structs/test_causes.py
  tests/causation/test_kwargs.py
  tests/hierarchies/test_contextual_owner.py
  tests/invocations/test_callbacks.py
  tests/lifecycles/test_real_invocation.py
  tests/registries/conftest.py
Labels: refactoring

#757 Unify the publicly exported sync/async daemon-stopping flag
  docs/kwargs.rst
  examples/11-filtering-handlers/example.py
  examples/14-daemons/example.py
  kopf/__init__.py
  kopf/reactor/causation.py
  kopf/reactor/daemons.py
  kopf/reactor/effects.py
  kopf/structs/callbacks.py
  kopf/structs/primitives.py
  tests/causation/test_kwargs.py
  tests/handling/daemons/conftest.py
  tests/handling/daemons/test_timer_errors.py
  tests/handling/daemons/test_timer_intervals.py
  tests/handling/daemons/test_timer_triggering.py
Labels: enhancement, refactoring

#760 Avoid losing the existing stopping reasons, if any
  kopf/structs/primitives.py
Labels: bug, refactoring

#763 Refactor decouple memories
  kopf/reactor/admission.py
  kopf/reactor/daemons.py
  kopf/reactor/effects.py
  kopf/reactor/indexing.py
  kopf/reactor/processing.py
  kopf/structs/containers.py
  kopf/structs/throttlers.py
  tests/basic-structs/test_memories.py
  tests/handling/daemons/test_daemon_termination.py
  tests/handling/indexing/test_index_exclusion.py
  tests/timing/test_throttling.py
Labels: refactoring

#766 Document the layered architecture
  docs/.gitattributes
  docs/architecture-layers.png
  docs/architecture-layers.xml
  docs/architecture.rst
  docs/index.rst
Labels: documentation

#769 Fix an issue with Click 8.0.0 for custom type double-conversion
  kopf/cli.py
Labels: bug, critical

#770 Hint a possible action when API authentication errors occur
  docs/authentication.rst
  kopf/_cogs/clients/auth.py
  kopf/_cogs/structs/credentials.py
  kopf/_core/intents/piggybacking.py
  tests/authentication/test_vault.py
  tests/k8s/test_creating.py
  tests/k8s/test_errors.py
  tests/k8s/test_list_objs.py
  tests/k8s/test_patching.py
Labels: enhancement

#771 Fall back to rudimentary login handlers if the clients are absent
  docs/authentication.rst
  kopf/__init__.py
  kopf/_core/intents/piggybacking.py
  kopf/_core/intents/registries.py
  setup.py
  tests/authentication/test_login_kubeconfig.py
  tests/authentication/test_login_serviceaccount.py
Labels: enhancement

#772 Use only pure f-strings for logs, avoid %s/%r formatting
  docs/walkthrough/creation.rst
  docs/walkthrough/deletion.rst
  docs/walkthrough/updates.rst
  kopf/_cogs/aiokits/aiotasks.py
  kopf/_cogs/clients/watching.py
  kopf/_core/actions/execution.py
  kopf/_core/engines/probing.py
  kopf/_core/reactor/processing.py
  kopf/_core/reactor/queueing.py
  kopf/_core/reactor/running.py
Labels: refactoring

#773 Fix the documentation cross-linking
  docs/admission.rst
  docs/authentication.rst
  docs/cli.rst
  docs/conf.py
  docs/configuration.rst
  docs/continuity.rst
  docs/contributing.rst
  docs/daemons.rst
  docs/errors.rst
  docs/filters.rst
  docs/handlers.rst
  docs/hierarchies.rst
  docs/idempotence.rst
  docs/index.rst
  docs/indexing.rst
  docs/kwargs.rst
  docs/peering.rst
  docs/testing.rst
  docs/timers.rst
  docs/tips-and-tricks.rst
  docs/troubleshooting.rst
  docs/walkthrough/deletion.rst
  docs/walkthrough/resources.rst
  docs/walkthrough/starting.rst
  kopf/_cogs/aiokits/aioenums.py
Labels: documentation

#733 Parse E2E flags/configs with AST instead of RegExps
  examples/03-exceptions/example.py
  examples/08-events/example.py
  examples/10-builtins/example.py
  examples/13-hooks/example.py
  examples/14-daemons/example.py
  examples/16-indexing/example.py
  examples/17-admission/example.py
  examples/99-all-at-once/example.py
  requirements.txt
  tests/e2e/test_examples.py
Labels: automation

#775 Correct some code-formatting and linting issues (for pre-commit)
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  DEVELOPMENT.md
  README.md
  SECURITY.md
  docs/requirements.txt
  examples/02-children/example.py
  examples/05-handlers/README.md
  kopf/_cogs/aiokits/aiotasks.py
  kopf/_cogs/configs/configuration.py
  kopf/_cogs/structs/dicts.py
  kopf/_core/actions/execution.py
  kopf/_core/actions/loggers.py
  kopf/_core/engines/peering.py
  kopf/_core/intents/handlers.py
  kopf/_core/reactor/running.py
  kopf/py.typed
  requirements.txt
  tests/authentication/test_login_kubeconfig.py
  tests/handling/daemons/conftest.py
  tests/persistence/test_storing_of_progress.py
Labels: refactoring

#776 Lint the source code with pre-commit
  .github/workflows/ci.yaml
  .github/workflows/thorough.yaml
  .pre-commit-config.yaml
  README.md
  docs/contributing.rst
  requirements.txt
  tests/posting/test_poster.py
Labels: automation

#777 Expose Kopf's version in user-agent & in logs
  kopf/__init__.py
  kopf/_cogs/clients/auth.py
  kopf/_cogs/helpers/versions.py
  kopf/_core/reactor/running.py
  tests/conftest.py
  tests/test_versions.py
Labels: enhancement

#778 Disable branch checks for pre-commit
  .pre-commit-config.yaml
Labels: automation

#780 Propagate the sub-handling context to sub-sub-handlers
  kopf/_core/reactor/subhandling.py
  tests/handling/subhandling/test_subhandling.py
Labels: bug
